drop table if exists eml_areas;
drop table if exists EML_FREIGHT_TEMPLATE;
drop table if exists EML_CARRY_MODE;
drop table if exists EML_LOGISTICS;

create table eml_areas (
	id varchar(6) generated by default as identity,
	area_code varchar(6) not null,
	area_name varchar(128) not null,
	parent_code varchar(6) not null,
	primary key (id)
	);

create table EML_FREIGHT_TEMPLATE
(
	ID VARCHAR(16),
	STORE_ID varchar(16), 
	FREIGHT_NAME VARCHAR(40),
	STATUS CHAR(1),
	REMARK varchar(225),
	PRIMARY KEY (ID)
);

CREATE TABLE EML_CARRY_MODE
(
	ID VARCHAR(16),
	TEMP_ID VARCHAR(16),
	SERVICE_TYPE VARCHAR(16),--EMS/POST/EXPRESS
	AREAS VARCHAR(200),
	AREAS_CODES VARCHAR(225);
	FEE VARCHAR(10),
	ADDED_FEE VARCHAR(10),
	IS_DEFAULT CHAR(1),  --0：默认，1：地区
	PRIMARY KEY ( ID )
);

create table EML_LOGISTICS (
    ID varchar(16),
    ORDER_ID varchar(32),				--订单编号
    LOGIS_COMPANY_CODE varchar(32),		--物流公司代码
    MAIL_NO varchar(20),				--运单号码
    SEND_ADDRESS_ID varchar(16),		--发货地址编号
    CANCEL_ADDRESS_ID varchar(16),		--退货地址编号
    RECEIVER_NAME varchar(20),			--收货人姓名
    RECEIVER_MOBILE_PHONE varchar(11),	--收货人手机号码
    RECEIVER_TELEPHONE varchar(18),		--收货人固定电话
    RECEIVER_ZIP_CODE varchar(6),		--收货邮编
    RECEIVER_AREAS varchar(100),		--收货所在地
    RECEIVER_ADDRESS varchar(200),		--收货详细地址
    RECEIVER_AREAS_CODE varchar(6),		--收货所在地区县区号
	CREATE_TIME TIMESTAMP,				--发货完成时间
    REMARK varchar(225), 				--备注
    primary key (ID)   
);